name: Java CI
on: push
jobs:
  clone:
    name: Clone & Package
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3   
      - name: Upload Code
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: . 
  build:
    name: Build & Test
    needs: [clone]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download Code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Build
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
