name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    name: Clone + Build
    steps:
      - name: Clone
        uses: actions/checkout@v3   
      - name: Build
        run: ci/build-app.sh